# Generated by Django 5.2.8 on 2025-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
