# Generated by Django 5.2.8 on 2025-11-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncomeDate', models.DateField(blank=True, null=True)),
                ('Category', models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('freelance', 'Freelance'), ('gift', 'Gift'), ('investment', 'Investment'), ('other', 'Other')], default='other', max_length=50)),
                ('Source', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
                ('NotDate', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
